ARG NODE_VERSION=18.16.1

FROM node:${NODE_VERSION}-bullseye

RUN apt-get update \
  && apt-get --no-install-recommends -y install gnupg2 ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists \
  && yarn global add pnpm

WORKDIR /workspaces/quiz-rally/

COPY ./.git /workspaces/quiz-rally/.git
COPY ./package.json ./pnpm-lock.yaml /workspaces/quiz-rally/
RUN pnpm install --frozen-lockfile
